#!/bin/bash

# Quick deployment script for Hostinger
# This script helps you deploy the latest changes to your live server

echo "======================================"
echo "MHA Plus - Quick Deployment Script"
echo "======================================"
echo ""
echo "Latest local commits:"
git log --oneline -5
echo ""
echo "======================================"
echo "DEPLOYMENT INSTRUCTIONS"
echo "======================================"
echo ""
echo "The overlay enhancement is committed locally (a0f517d)."
echo "Changes made:"
echo "  - Stronger gradient: from-black/95 via-black/70 to-black/30"
echo "  - Added backdrop-blur for better text visibility"
echo ""
echo "To deploy to mhaplus.com, run these commands:"
echo ""
echo "1. SSH into Hostinger:"
echo "   ssh your-username@your-server-ip"
echo ""
echo "2. Navigate to website directory:"
echo "   cd domains/mhaplus.com/public_html"
echo "   # OR"
echo "   cd public_html"
echo ""
echo "3. Pull latest changes:"
echo "   git pull origin main"
echo "   # OR if that doesn't work:"
echo "   git pull https://github.com/BlindJamil/mha_plus.git main"
echo ""
echo "4. Clear all caches:"
echo "   php artisan optimize:clear"
echo ""
echo "5. Exit SSH and refresh browser:"
echo "   exit"
echo "   # Then press: Cmd + Shift + R"
echo ""
echo "======================================"
echo "OR Use Hostinger Control Panel:"
echo "======================================"
echo "1. Login to Hostinger"
echo "2. Go to: Advanced → Git"
echo "3. Click 'Pull' button"
echo "4. Refresh browser: Cmd + Shift + R"
echo ""
